const { test, expect } = require("@playwright/test");
const { pom } = require("../pages/pom.page");

test("Verify user can register an account via phone number", async ({context, page }) => {
    const pageom = new pom(page)
    await pageom.goToHomePage()
    await pageom.signUpButton()
    await pageom.changeCountry()
    await pageom.scroll()
    await pageom.chooseUS()
    await pageom.fillRegisterFields()
    await pageom.checkTerms()
    await pageom.createAccountB()
    await page.waitForTimeout(6000)
    const page1 = await context.newPage()
    await page1.goto("https://receive-smss.live/messages?n=12183924371")
    const text = (await page1.getByText("Your Menu verification code is ").nth(0).innerText()).valueOf()
    const sms = text.slice(-5, -1)
    await page1.close()
    page.fill("//input[@data-id='0']", sms)
    await pageom.verificationButton()
    await pageom.userIcon()
    await pageom.accountSettings()
    const number = page.locator("(//span[text()='Phone Number']/following::input)[1]")
    await expect(number).toHaveValue("+1" + pageom.logNumberAM)
})

// test("Verify user can register an account with Google account 	", async ({ page }) => {
//     const pageom = new pom(page)
//     await pageom.goToHomePage()
//     await pageom.signUpButton()
//     await pageom.checkTerms()
//     await pageom.googleButton()
//     await page.waitForTimeout(5000)
//     await pageom.googleButton()
//     const page1Promise = page.waitForEvent('popup')
//     const page1 = await page1Promise
//     await page1.getByRole('textbox', { name: 'Email or phone' }).fill(pageom.googleMail)
//     await page1.getByRole('button', { name: 'Next' }).click()
//     await page1.getByRole('textbox', { name: 'Enter your password' }).fill(pageom.googlePassword)
//     await page1.getByRole('button', { name: 'Next' }).click()
//     await pageom.userIcon()
//     await pageom.accountSettings()
//     const mail = page.locator("(//span[text()='Email']/following::input)[1]")
//     expect(mail).toHaveValue(pageom.googleMail)
// })