import { expect, test } from "@playwright/test";
import { pom } from "../pages/pom.page";

test("Verify user can reset password via email address ", async({ context, page }) => {
    const pageom = new pom(page)
    await pageom.goToHomePage()
    await pageom.signInButtonH()
    await pageom.forgotPasswordButton()
    await page.click("(//input[@type='radio'])[1]")
    await page.fill("//input[@placeholder='Enter your email address']", pageom.logMail)
    await pageom.sendVeryficationCodeB()
    const page1 = await context.newPage()
    await page1.goto('https://yopmail.com/')
    await page1.getByPlaceholder('Enter your inbox here').fill('menu1234')
    await page1.getByPlaceholder('Enter your inbox here').press('Enter')
    let text = (await page1.frameLocator('iframe[name="ifmail"]').locator('font[style="font-size: 48px; line-height: 56px"]').innerText()).valueOf()
    await page1.close()
    await page.fill("//input[@data-id='0']", text)
    await pageom.verificationButton()
    await pageom.newPassword()
    await pageom.signInButtonS()
    await page.waitForURL("https://menu.am/en/auth-sign-in")
})

test("Verify user can reset password via phon number", async ({ context, page }) => {
    const pageom = new pom(page)
    await pageom.goToHomePage()
    await pageom.signInButtonH()
    await pageom.forgotPasswordButton()
    await pageom.changeCountry()
    await pageom.scroll()
    await pageom.chooseUS()
    await pageom.fillNumber()
    await pageom.sendVeryficationCodeB()
    await page.waitForTimeout(5000)
    const page1 = await context.newPage()
    await page1.goto("https://receive-smss.live/messages?n=12183924371")
    const text = (await page1.getByText("Your Menu verification code is ").nth(0).innerText()).valueOf()
    const sms = text.slice(-5, -1)
    await page1.close()
    page.fill("//input[@data-id='0']", sms)
    await pageom.verificationButton()
    await pageom.newPassword()
    await pageom.signInButtonS()
    await page.waitForURL("https://menu.am/en/auth-sign-in")
})